apiVersion: apps/v1
kind: Deployment
metadata:
  name: tlwe2021-nodejs
spec:
  selector:
    matchLabels:
      app: tlwe2021-nodejs
  template:
    metadata:
      labels:
        app: tlwe2021-nodejs
    spec:
      containers:
      - name: tlwe2021-nodejs
        image: ghcr.io/thenativeweb/tlwe2021-nodejs:latest
        env:
        - name: NODE_ENV
          value: production
        ports:
        - name: http
          containerPort: 8080
      imagePullSecrets:
      - name: ghcr
      automountServiceAccountToken: false
---
kind: Service
apiVersion: v1
metadata:
  name: tlwe2021-nodejs
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: tlwe2021-nodejs
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tlwe2021-nodejs
spec:
  ingressClassName: nginx
  rules:
  - host: tlwe.akampf.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tlwe2021-nodejs
            port: 
              name: http
